#!/usr/bin/python3
# library to get arguments
import sys

def factorize(num):
    for i in range(2, num//2 + 1):
        if num % i == 0:
            print(f"{num}={i}*{num//i}")
            return

if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} <file>")
    sys.exit(1)

filename = sys.argv[1]

try:
    with open(filename, "r") as file:
        for line in file:
            num = int(line.strip())
            factorize(num)
except IOError:
    print("Error opening file")
    sys.exit(1)
    
# autostart
factorize()
